name: deploy_frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy to https://vbi-ui.netlify.app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Build
        run: |
          cd vbi-ui
          echo "REACT_APP_BASE_URL=https://visual-bi-music-app.herokuapp.com" > .env
          echo "REACT_APP_AUTH0_AUD_URL=https://visual-bi-music-app.herokuapp.com" >> .env
          echo "REACT_APP_AUTH0_DOMAIN=nikhil-001mehta.auth0.com" >> .env
          echo "REACT_APP_AUTH0_CLIENT_ID=9tZMuPN4U302UqDKHjV64vRX4yns1BFR" >> .env
          yarn --frozen-lockfile
          yarn build

      - name: Install netlify-cli
        run: |
          cd vbi-ui
          npm install netlify-cli

      - name: Deploy to netlify
        run: |
          cd vbi-ui
          npx netlify deploy --site 75c91364-611d-499a-9cfb-b9506c82b3c7 --dir build --auth ${{secrets.NETLIFY_AUTH_TOKEN}} --prod
