name: Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1

      - name: Add remote origin
        run: |
          cd vbi-backend
          git init
          git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/visual-bi-music-app.git

      - name: Deploy backend to heroku
        run: |
          cd vbi-backend
          git push --force heroku master

